/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#00210c",
        "surface-bright": "#f7f9ff",
        "on-error-container": "#93000a",
        "surface-dim": "#c9dcf3",
        "on-secondary-fixed-variant": "#19512d",
        "tertiary-container": "#ff9875",
        "on-surface-variant": "#3d4a3e",
        "background": "#f7f9ff",
        "on-tertiary-fixed-variant": "#793015",
        "outline-variant": "#bbcbbb",
        "outline": "#6c7b6d",
        "on-primary-fixed-variant": "#005228",
        "on-primary-fixed": "#00210c",
        "tertiary": "#98472a",
        "secondary-container": "#b5f1c0",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#9ad4a5",
        "primary-container": "#2ecc71",
        "primary-fixed": "#6bfe9c",
        "on-tertiary-fixed": "#390c00",
        "tertiary-fixed": "#ffdbd0",
        "inverse-on-surface": "#e8f2ff",
        "secondary-fixed": "#b5f1c0",
        "tertiary-fixed-dim": "#ffb59d",
        "on-primary-container": "#005027",
        "surface-tint": "#006d37",
        "error-container": "#ffdad6",
        "primary": "#006d37",
        "on-tertiary-container": "#772e14",
        "on-background": "#091d2e",
        "surface": "#f7f9ff",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#396f48",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#4ae183",
        "surface-container-highest": "#d1e4fb",
        "surface-container-high": "#d9eaff",
        "on-error": "#ffffff",
        "on-surface": "#091d2e",
        "surface-container": "#e3efff",
        "surface-container-low": "#edf4ff",
        "surface-variant": "#d1e4fb",
        "on-secondary": "#ffffff",
        "inverse-surface": "#203243",
        "secondary": "#336943",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#4ae183"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
